#include <M5Core2.h>

namespace theme {
ButtonColors INVIS_BUTTON_OFF_COLORS = {WHITE, WHITE, WHITE};
ButtonColors INVIS_BUTTON_ON_COLORS = {0x7193, 0x7193, WHITE};

ButtonColors CHECK_BUTTON_OFF_COLORS = {GREEN, WHITE, WHITE};
ButtonColors CHECK_BUTTON_ON_COLORS = {DARKGREEN, WHITE, WHITE};

ButtonColors CANCEL_BUTTON_OFF_COLORS = {RED, WHITE, WHITE};
ButtonColors CANCEL_BUTTON_ON_COLORS = {MAROON, WHITE, WHITE};

ButtonColors RESET_BUTTON_OFF_COLORS = {PURPLE, WHITE, WHITE};
ButtonColors RESET_BUTTON_ON_COLORS = {0x7193, WHITE, WHITE};
} // namespace theme